language: clojure
lein: lein
dist: xenial
addons:
  ssh_known_hosts: shrimp.octet.services
services:
  - docker

before_install:
  - export BARGE_URL=http://52.187.164.74
  - scripts/setup_for_remote_barge.sh $BARGE_URL
script: lein do clean, test

branches:
  only:
    - master
